### ISSUE TITLE
[sys.monitoring] Tracing execution flow

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1420]
This covers all logic related to execution flow: stack trace, stepping, breakpoints, exceptions etc.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/debugpy/issues/1421
- [ ] https://github.com/microsoft/debugpy/issues/1424
- [ ] https://github.com/microsoft/debugpy/issues/1429
- [ ] https://github.com/microsoft/debugpy/issues/1436
- [ ] https://github.com/microsoft/debugpy/issues/1472
- [ ] https://github.com/microsoft/debugpy/issues/1510
```
