### ISSUE TITLE
[sys.monitoring] Breakpoints

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1429]
Handle `setBreakpoints` DAP request.
```[tasklist]
### Tasks
- [x] source (line/column) breakpoints
- [ ] https://github.com/microsoft/debugpy/issues/1430
- [ ] https://github.com/microsoft/debugpy/issues/1431
- [ ] https://github.com/microsoft/debugpy/issues/1432
- [ ] https://github.com/microsoft/debugpy/issues/1433
- [ ] https://github.com/microsoft/debugpy/issues/1434
- [ ] https://github.com/microsoft/debugpy/issues/1435
- [ ] https://github.com/microsoft/debugpy/issues/1466
- [ ] https://github.com/microsoft/debugpy/issues/1467
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
