### ISSUE TITLE
[sys.monitoring] Expression evaluation

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1437]
This covers all logic related to evaluating expressions and rendering values: displaying variables and expanding their children, Watch, Auto, editing values etc.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/debugpy/issues/1438
- [ ] https://github.com/microsoft/debugpy/issues/1439
- [ ] https://github.com/microsoft/debugpy/issues/1440
- [ ] https://github.com/microsoft/debugpy/issues/1441
- [ ] https://github.com/microsoft/debugpy/issues/1442
- [ ] https://github.com/microsoft/debugpy/issues/1446
- [ ] https://github.com/microsoft/debugpy/issues/1534
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
