### ISSUE TITLE
[sys.monitoring] [meta] Variables

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1438]
Handling DAP `variables` and `scopes` requests for stack frames.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/debugpy/issues/1443
- [ ] https://github.com/microsoft/debugpy/issues/1444
- [ ] https://github.com/microsoft/debugpy/issues/1445
```
