### ISSUE TITLE
[sys.monitoring] Variable children

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1439]
Handle DAP `variables` request to retrieve children of previously retrieved variables. This includes tracking lifetime of retrieved variables and disposing of them as needed.

For long collections, a subset of children should be reported, with pagination or other such facilities provided to view the rest of the data.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/debugpy/issues/1456
- [ ] https://github.com/microsoft/debugpy/issues/1457
- [ ] https://github.com/microsoft/debugpy/issues/1458
- [ ] https://github.com/microsoft/debugpy/issues/1459
- [ ] https://github.com/microsoft/debugpy/issues/1460
- [ ] https://github.com/microsoft/debugpy/issues/1461
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
