### ISSUE TITLE
[sys.monitoring] Variable values

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1440]
This covers computation of values for variables, i.e. DAP `Variable.value` and handling of other properties that affect it. 
The format for values is that of Python `repr()`, but this includes handling large and/or recursive collections properly by intelligently shortening the value as needed ("safe repr").
```[tasklist]
### Tasks
- [x] Basic repr() for simple types
- [ ] https://github.com/microsoft/debugpy/issues/1447
- [ ] https://github.com/microsoft/debugpy/issues/1448
- [ ] https://github.com/microsoft/debugpy/issues/1449
- [ ] https://github.com/microsoft/debugpy/issues/1450
- [ ] https://github.com/microsoft/debugpy/issues/1451
```

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
